<?php
require_once('clients/main.php');
require_once('forms/main.php');
require_once('invoice/main.php');
require_once('project/main.php');
require_once('quote/main.php');
require_once('task/main.php');
require_once('teams/main.php');
require_once('templates/main.php');
require_once('terms/main.php');
require_once('leadforms/main.php');
require_once('leads/main.php');
require_once('faq/main.php');