<?php return array(
	'sans-serif'       => array(
		'normal'      => $fontDir . '/Helvetica',
		'bold'        => $fontDir . '/Helvetica-Bold',
		'italic'      => $fontDir . '/Helvetica-Oblique',
		'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
	),
	'times'            => array(
		'normal'      => $fontDir . '/Times-Roman',
		'bold'        => $fontDir . '/Times-Bold',
		'italic'      => $fontDir . '/Times-Italic',
		'bold_italic' => $fontDir . '/Times-BoldItalic',
	),
	'times-roman'      => array(
		'normal'      => $fontDir . '/Times-Roman',
		'bold'        => $fontDir . '/Times-Bold',
		'italic'      => $fontDir . '/Times-Italic',
		'bold_italic' => $fontDir . '/Times-BoldItalic',
	),
	'courier'          => array(
		'normal'      => $fontDir . '/Courier',
		'bold'        => $fontDir . '/Courier-Bold',
		'italic'      => $fontDir . '/Courier-Oblique',
		'bold_italic' => $fontDir . '/Courier-BoldOblique',
	),
	'helvetica'        => array(
		'normal'      => $fontDir . '/Helvetica',
		'bold'        => $fontDir . '/Helvetica-Bold',
		'italic'      => $fontDir . '/Helvetica-Oblique',
		'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
	),
	'zapfdingbats'     => array(
		'normal'      => $fontDir . '/ZapfDingbats',
		'bold'        => $fontDir . '/ZapfDingbats',
		'italic'      => $fontDir . '/ZapfDingbats',
		'bold_italic' => $fontDir . '/ZapfDingbats',
	),
	'symbol'           => array(
		'normal'      => $fontDir . '/Symbol',
		'bold'        => $fontDir . '/Symbol',
		'italic'      => $fontDir . '/Symbol',
		'bold_italic' => $fontDir . '/Symbol',
	),
	'serif'            => array(
		'normal'      => $fontDir . '/Times-Roman',
		'bold'        => $fontDir . '/Times-Bold',
		'italic'      => $fontDir . '/Times-Italic',
		'bold_italic' => $fontDir . '/Times-BoldItalic',
	),
	'monospace'        => array(
		'normal'      => $fontDir . '/Courier',
		'bold'        => $fontDir . '/Courier-Bold',
		'italic'      => $fontDir . '/Courier-Oblique',
		'bold_italic' => $fontDir . '/Courier-BoldOblique',
	),
	'fixed'            => array(
		'normal'      => $fontDir . '/Courier',
		'bold'        => $fontDir . '/Courier-Bold',
		'italic'      => $fontDir . '/Courier-Oblique',
		'bold_italic' => $fontDir . '/Courier-BoldOblique',
	),
	'dejavu sans'      => array(
		'bold'        => $fontDir . '/DejaVuSans-Bold',
		'bold_italic' => $fontDir . '/DejaVuSans-BoldOblique',
		'italic'      => $fontDir . '/DejaVuSans-Oblique',
		'normal'      => $fontDir . '/DejaVuSans',
	),
	'dejavu sans mono' => array(
		'bold'        => $fontDir . '/DejaVuSansMono-Bold',
		'bold_italic' => $fontDir . '/DejaVuSansMono-BoldOblique',
		'italic'      => $fontDir . '/DejaVuSansMono-Oblique',
		'normal'      => $fontDir . '/DejaVuSansMono',
	),
	'dejavu serif'     => array(
		'bold'        => $fontDir . '/DejaVuSerif-Bold',
		'bold_italic' => $fontDir . '/DejaVuSerif-BoldItalic',
		'italic'      => $fontDir . '/DejaVuSerif-Italic',
		'normal'      => $fontDir . '/DejaVuSerif',
	),
	'cabin'            => array(
		'normal'      => $fontDir . '/cabin_normal_4312cbb7d0e92c77e4a2d09536e7c38b',
		'italic'      => $fontDir . '/cabin_italic_62e8ccc069aaf647bf81e424c9fe6632',
		'500_italic'  => $fontDir . '/cabin_500_italic_dd98edea3662d3381b0b9c72fa9b88e2',
		'600_italic'  => $fontDir . '/cabin_600_italic_ef5437511a71f0390f32e5f9d0b9cd6f',
		'bold_italic' => $fontDir . '/cabin_bold_italic_f0bad4fc70c397fb2b88d4ca2666932f',
		'500'         => $fontDir . '/cabin_500_33f0ad1afea9904bcb2a57ad678328a5',
		'600'         => $fontDir . '/cabin_600_6165e938cb05956f725851f4621feac4',
		'bold'        => $fontDir . '/cabin_bold_67ce371b937f5e62b8865e62efb0e61b',
	),
	'fontawesome'      => array(
		'normal' => $fontDir . '/fontawesome_normal_a07c54af815ea54af1b5e5aa13cc5f8b',
	),
); 
